#!/bin/bash

outfile=data/links.txt
bin/randomlinks -ruleset targeted > $outfile
echo "Random links created in $outfile."
echo ""
echo "To create an image with these links, run"
echo ""
echo "> /path/to/circos -conf etc/circos.conf"
echo ""
echo "from this directory."

