#!/bin/bash

echo "parsing data"
cat data/individuals.txt | bin/parse-category -conf etc/parse-category.conf > data/links.txt 2> data/karyotype.txt

echo "Links created in data/links.txt and karyotype file in data/karyotype.txt."
echo ""
echo "To create an image with these data, run"
echo ""
echo "> /path/to/circos -conf etc/circos.conf"
echo ""
echo "from this directory."




